image: python

stages: 
  - build
  - test
  - deploy

build-job:
  stage: build 
  script: 
    - python3 - V

test-job: 
  stage: test
  script:
    - python3 test.py
  
deploy-job:
  stage: deply
  script:
    - echo "Finalizado!"
    
